"Filed out from Dolphin Smallalk"!

Smalltalk at: #AllChessFiles put: (PoolConstantsDictionary named: #AllChessFiles)!
AllChessFiles at: 'a' put: (Object fromBinaryStoreBytes: 
(ByteArray fromBase64String: 'IVNUQiA0IAYCCQBDaGVzc0ZpbGUAAAAAUgAAAAEAAABh'))!
AllChessFiles at: 'b' put: (Object fromBinaryStoreBytes: 
(ByteArray fromBase64String: 'IVNUQiA0IAYCCQBDaGVzc0ZpbGUAAAAAUgAAAAEAAABi'))!
AllChessFiles at: 'c' put: (Object fromBinaryStoreBytes: 
(ByteArray fromBase64String: 'IVNUQiA0IAYCCQBDaGVzc0ZpbGUAAAAAUgAAAAEAAABj'))!
AllChessFiles at: 'd' put: (Object fromBinaryStoreBytes: 
(ByteArray fromBase64String: 'IVNUQiA0IAYCCQBDaGVzc0ZpbGUAAAAAUgAAAAEAAABk'))!
AllChessFiles at: 'e' put: (Object fromBinaryStoreBytes: 
(ByteArray fromBase64String: 'IVNUQiA0IAYCCQBDaGVzc0ZpbGUAAAAAUgAAAAEAAABl'))!
AllChessFiles at: 'f' put: (Object fromBinaryStoreBytes: 
(ByteArray fromBase64String: 'IVNUQiA0IAYCCQBDaGVzc0ZpbGUAAAAAUgAAAAEAAABm'))!
AllChessFiles at: 'g' put: (Object fromBinaryStoreBytes: 
(ByteArray fromBase64String: 'IVNUQiA0IAYCCQBDaGVzc0ZpbGUAAAAAUgAAAAEAAABn'))!
AllChessFiles at: 'h' put: (Object fromBinaryStoreBytes: 
(ByteArray fromBase64String: 'IVNUQiA0IAYCCQBDaGVzc0ZpbGUAAAAAUgAAAAEAAABo'))!
AllChessFiles shrink!
