"Filed out from Dolphin Smallalk"!

Smalltalk at: #AllChessFiles put: (PoolConstantsDictionary named: #AllChessFiles)!
AllChessFiles at: 'a' put: (Object fromBinaryStoreBytes: 
(ByteArray fromBase64String: 'IVNUQiA0IAYBCQBDaGVzc0ZpbGVSAAAAAQAAAGE='))!
AllChessFiles at: 'b' put: (Object fromBinaryStoreBytes: 
(ByteArray fromBase64String: 'IVNUQiA0IAYBCQBDaGVzc0ZpbGVSAAAAAQAAAGI='))!
AllChessFiles at: 'c' put: (Object fromBinaryStoreBytes: 
(ByteArray fromBase64String: 'IVNUQiA0IAYBCQBDaGVzc0ZpbGVSAAAAAQAAAGM='))!
AllChessFiles at: 'd' put: (Object fromBinaryStoreBytes: 
(ByteArray fromBase64String: 'IVNUQiA0IAYBCQBDaGVzc0ZpbGVSAAAAAQAAAGQ='))!
AllChessFiles at: 'e' put: (Object fromBinaryStoreBytes: 
(ByteArray fromBase64String: 'IVNUQiA0IAYBCQBDaGVzc0ZpbGVSAAAAAQAAAGU='))!
AllChessFiles at: 'f' put: (Object fromBinaryStoreBytes: 
(ByteArray fromBase64String: 'IVNUQiA0IAYBCQBDaGVzc0ZpbGVSAAAAAQAAAGY='))!
AllChessFiles at: 'g' put: (Object fromBinaryStoreBytes: 
(ByteArray fromBase64String: 'IVNUQiA0IAYBCQBDaGVzc0ZpbGVSAAAAAQAAAGc='))!
AllChessFiles at: 'h' put: (Object fromBinaryStoreBytes: 
(ByteArray fromBase64String: 'IVNUQiA0IAYBCQBDaGVzc0ZpbGVSAAAAAQAAAGg='))!
AllChessFiles shrink!
