"Filed out from Dolphin Smallalk"!

ChessMoveCategory subclass: #ChessCastleMove
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessCastleMove guid: (GUID fromString: '{e4dd4a6c-d882-4a95-bbea-7b6c0c30669e}')!
ChessCastleMove comment: ''!
!ChessCastleMove categoriesForClass!Unclassified! !
!ChessCastleMove methodsFor!

isCastle

	^true! !
!ChessCastleMove categoriesForMethods!
isCastle!public! !
!

