"Filed out from Dolphin Smallalk"!

ChessGameExecutor subclass: #ChessPgnGameExecutor
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessPgnGameExecutor guid: (GUID fromString: '{2ea8aabd-5a82-43db-98a8-b9af9f6b2fad}')!
ChessPgnGameExecutor comment: ''!
!ChessPgnGameExecutor categoriesForClass!Unclassified! !
!ChessPgnGameExecutor methodsFor!

setPgnMoves: pgnMoves

	game setPgnMoves: pgnMoves! !
!ChessPgnGameExecutor categoriesForMethods!
setPgnMoves:!public! !
!

