"Filed out from Dolphin Smallalk"!

Object subclass: #ChessTemplate
	instanceVariableNames: 'chunks'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessTemplate guid: (GUID fromString: '{56dcd451-4d4c-4f27-8439-650a3827d39f}')!
ChessTemplate comment: ''!
!ChessTemplate categoriesForClass!Unclassified! !
!ChessTemplate class methodsFor!

icon
	^Icon fromId: 'RegKeyAbstract.ico'! !
!ChessTemplate class categoriesForMethods!
icon!public! !
!

