"Filed out from Dolphin Smallalk"!

ChessEvaluationAlgorithm subclass: #ChessboardTerritoryEvaluation
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessboardTerritoryEvaluation guid: (GUID fromString: '{35dba98e-cf04-439c-8ccf-0137f9f066df}')!
ChessboardTerritoryEvaluation comment: ''!
!ChessboardTerritoryEvaluation categoriesForClass!Unclassified! !
