"Filed out from Dolphin Smallalk"!

Presenter subclass: #ChessAbstractPresenter
	instanceVariableNames: 'systemRoot'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessAbstractPresenter guid: (GUID fromString: '{e4618e4b-6111-4fd4-b85e-e4e78f54f790}')!
ChessAbstractPresenter comment: ''!
!ChessAbstractPresenter categoriesForClass!Unclassified! !
!ChessAbstractPresenter methodsFor!

setRoot: aSystemRoot

	systemRoot := aSystemRoot! !
!ChessAbstractPresenter categoriesForMethods!
setRoot:!private! !
!

