"Filed out from Dolphin Smallalk"!

Object subclass: #ChessMoveCategory
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessMoveCategory guid: (GUID fromString: '{b63176c2-3d16-45a1-962d-2060353b7c68}')!
ChessMoveCategory comment: ''!
!ChessMoveCategory categoriesForClass!Unclassified! !
!ChessMoveCategory methodsFor!

isCastle

	^false!

isEnPassant

	^false! !
!ChessMoveCategory categoriesForMethods!
isCastle!public! !
isEnPassant!public! !
!

!ChessMoveCategory class methodsFor!

icon

	^Icon fromId: 'STON.ico'! !
!ChessMoveCategory class categoriesForMethods!
icon!public! !
!

