"Filed out from Dolphin Smallalk"!

ChessEngineTreeNode subclass: #ChessEngineOrientationTreeNode
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessEngineOrientationTreeNode guid: (GUID fromString: '{1f8d6f2e-6f48-406c-b3b1-409836acfd3a}')!
ChessEngineOrientationTreeNode comment: ''!
!ChessEngineOrientationTreeNode categoriesForClass!Unclassified! !
