"Filed out from Dolphin Smallalk"!

Object subclass: #ChessboardHeatMap
	instanceVariableNames: 'chessboard'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessboardHeatMap guid: (GUID fromString: '{c82a347d-fc06-40b5-a42a-c7490938fb3c}')!
ChessboardHeatMap comment: ''!
!ChessboardHeatMap categoriesForClass!Unclassified! !
!ChessboardHeatMap class methodsFor!

icon
	^Icon fromFile: (FileLocator imageRelative basePath, 'Ajedrez\chessboard-red-2.ico')! !
!ChessboardHeatMap class categoriesForMethods!
icon!public! !
!

