"Filed out from Dolphin Smallalk"!

ChessPinSearcherTest subclass: #ChessPartialPinSearcherTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessPartialPinSearcherTest guid: (GUID fromString: '{08b7cecf-1577-4453-bcd5-5a9403f0d8ad}')!
ChessPartialPinSearcherTest comment: ''!
!ChessPartialPinSearcherTest categoriesForClass!Unclassified! !
