"Filed out from Dolphin Smallalk"!

ChessTacticMoveSearcher subclass: #ChessPinSearcher
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessPinSearcher guid: (GUID fromString: '{02474420-2ba6-45ae-ac08-3e22f020cdfc}')!
ChessPinSearcher comment: ''!
!ChessPinSearcher categoriesForClass!Unclassified! !
!ChessPinSearcher methodsFor!

searchOnChessboardFor: aChessSide

	self subclassResponsibility! !
!ChessPinSearcher categoriesForMethods!
searchOnChessboardFor:!public! !
!

