"Filed out from Dolphin Smallalk"!

ChessPinSearcherTest subclass: #ChessSituationalPinSearcherTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessSituationalPinSearcherTest guid: (GUID fromString: '{c13aa58a-3435-496f-b01d-7bd106b609ae}')!
ChessSituationalPinSearcherTest comment: ''!
!ChessSituationalPinSearcherTest categoriesForClass!Unclassified! !
