"Filed out from Dolphin Smallalk"!

ChessTacticMoveSearcher subclass: #ChessSkewerSearcher
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessSkewerSearcher guid: (GUID fromString: '{7e4b0bdd-ef7a-44d7-8a97-e87b52172793}')!
ChessSkewerSearcher comment: ''!
!ChessSkewerSearcher categoriesForClass!Unclassified! !
!ChessSkewerSearcher methodsFor!

searchOnChessboardFor: aChessSide

	self subclassResponsibility! !
!ChessSkewerSearcher categoriesForMethods!
searchOnChessboardFor:!public! !
!

