"Filed out from Dolphin Smallalk"!

ChessTacticMoveSearcher subclass: #ChessDiscoveredAttackSearcher
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessDiscoveredAttackSearcher guid: (GUID fromString: '{46d1dcb2-bb44-4c93-83b1-3d783c02f115}')!
ChessDiscoveredAttackSearcher comment: ''!
!ChessDiscoveredAttackSearcher categoriesForClass!Unclassified! !
