"Filed out from Dolphin Smallalk"!

Object subclass: #ChessVector
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessVector guid: (GUID fromString: '{5e938d21-baad-4433-84d1-35bb0cbc5dfd}')!
ChessVector comment: ''!
!ChessVector categoriesForClass!Unclassified! !
!ChessVector class methodsFor!

icon

	^TextTileIcon text: (Character codePoint: 8658) asUtf16String fontName: 'Malgun Gothic'! !
!ChessVector class categoriesForMethods!
icon!public! !
!

