"Filed out from Dolphin Smallalk"!

ChessPinSearcher subclass: #ChessSituationalPinSearcher
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessSituationalPinSearcher guid: (GUID fromString: '{0b77567e-253f-49b8-b687-9df0b522d3d8}')!
ChessSituationalPinSearcher comment: ''!
!ChessSituationalPinSearcher categoriesForClass!Unclassified! !
!ChessSituationalPinSearcher methodsFor!

searchOnChessboardFor: aChessSide
	| pins |
	
	pins := Dictionary new.
	^pins! !
!ChessSituationalPinSearcher categoriesForMethods!
searchOnChessboardFor:!public! !
!

