"Filed out from Dolphin Smallalk"!

ChessSquareVector subclass: #ChessPieceVector
	instanceVariableNames: 'sourcePiece targetPiece'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessPieceVector guid: (GUID fromString: '{2ef7d806-c9fe-4711-afc5-1dbeb4a72664}')!
ChessPieceVector comment: ''!
!ChessPieceVector categoriesForClass!Unclassified! !
!ChessPieceVector class methodsFor!

icon

	^TextTileIcon text: (Character codePoint: 11162) asUtf16String fontName: 'Malgun Gothic'! !
!ChessPieceVector class categoriesForMethods!
icon!public! !
!

