"Filed out from Dolphin Smallalk"!

ChessSkewerSearcher subclass: #ChessRelativeSkewerSearcher
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessRelativeSkewerSearcher guid: (GUID fromString: '{e43633ea-81c6-42eb-919f-f89de17e1f72}')!
ChessRelativeSkewerSearcher comment: ''!
!ChessRelativeSkewerSearcher categoriesForClass!Unclassified! !
