"Filed out from Dolphin Smallalk"!

Object subclass: #ChessboardHeatMap
	instanceVariableNames: 'chessboard'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessboardHeatMap guid: (GUID fromString: '{c82a347d-fc06-40b5-a42a-c7490938fb3c}')!
ChessboardHeatMap comment: ''!
!ChessboardHeatMap categoriesForClass!Unclassified! !
!ChessboardHeatMap methodsFor!

evaluationPositionWith: anChessEvaluationAlgorithm! !
!ChessboardHeatMap categoriesForMethods!
evaluationPositionWith:!public! !
!

