"Filed out from Dolphin Smallalk"!

Object subclass: #ChessVisualEffectDefinition
	instanceVariableNames: 'isTopRendered'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessVisualEffectDefinition guid: (GUID fromString: '{947760e1-0767-4a8a-961d-611c1724d4bf}')!
ChessVisualEffectDefinition comment: ''!
!ChessVisualEffectDefinition categoriesForClass!Kernel-Objects! !
