"Filed out from Dolphin Smallalk"!

ChessPinSearcherTest subclass: #ChessRelativePinSearcherTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
ChessRelativePinSearcherTest guid: (GUID fromString: '{2ef4e80d-e820-4f83-a91e-f4614c326180}')!
ChessRelativePinSearcherTest comment: ''!
!ChessRelativePinSearcherTest categoriesForClass!Unclassified! !
