"Filed out from Dolphin Smallalk"!

ParallelProcessingServices subclass: #DolphinParallelProcessing
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
DolphinParallelProcessing guid: (GUID fromString: '{eede0358-67e0-404d-b919-45c90dc2c900}')!
DolphinParallelProcessing comment: ''!
!DolphinParallelProcessing categoriesForClass!Unclassified! !
