"Filed out from Dolphin Smallalk"!

ParallelProcessingServices subclass: #GemStoneParallelProcessing
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
GemStoneParallelProcessing guid: (GUID fromString: '{0e6fd370-baf3-42b1-b5ae-5d68dc1cfdd7}')!
GemStoneParallelProcessing comment: ''!
!GemStoneParallelProcessing categoriesForClass!Unclassified! !
