"Filed out from Dolphin Smallalk"!

ChessEvaluationAlgorithm subclass: #SimplePieceValueEvaluation
	instanceVariableNames: 'values'
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SimplePieceValueEvaluation guid: (GUID fromString: '{0c67a443-321e-4492-9a32-7e8ecc038a13}')!
SimplePieceValueEvaluation comment: ''!
!SimplePieceValueEvaluation categoriesForClass!Unclassified! !
