"Filed out from Dolphin Smallalk"!

ChessMovementRuleTest subclass: #SlidingPieceMovementEngineTest
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SlidingPieceMovementEngineTest guid: (GUID fromString: '{1e9681b8-57f4-4f58-b401-29775beca458}')!
SlidingPieceMovementEngineTest comment: ''!
!SlidingPieceMovementEngineTest categoriesForClass!Unclassified! !
