"Filed out from Dolphin Smallalk"!

ChessPiece subclass: #SlidingPiece
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SlidingPiece guid: (GUID fromString: '{95b13bae-ff2b-405e-93cb-448d73c5d7ac}')!
SlidingPiece comment: ''!
!SlidingPiece categoriesForClass!Kernel-Objects! !
!SlidingPiece methodsFor!

pruneUnreacheableSquaresFrom: aSquaresDictionary

	aSquaresDictionary pruneUnreachableSquaresFromSlidingPiece! !
!SlidingPiece categoriesForMethods!
pruneUnreacheableSquaresFrom:!new framework!public! !
!

!SlidingPiece class methodsFor!

blackCodePoint
	^8611! !
!SlidingPiece class categoriesForMethods!
blackCodePoint!public! !
!

